config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: redirect(path: '/recipes')
  resources :recipes, only: %i[index show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe_item.rb
# frozen_string_literal: true

class RecipeItem < ApplicationRecord
  class << self
    @@contentful_client = ContentfulClient.instance.client

    def get_recipe(recipe_id)
      contentful_recipe = @@contentful_client.entry(recipe_id)
      raise ArgumentError unless contentful_recipe

      {
        title: get_title(contentful_recipe),
        image_url: get_image_url(contentful_recipe),
        description: get_description(contentful_recipe),
        chef_name: get_chef_name(contentful_recipe),
        tags: get_tags(contentful_recipe)
      }
    end

    def fetch_recipes(skip = DEFAULT_SKIP, limit = DEFAULT_LIMIT)
      @@contentful_client.entries(
        content_type: RECIPE_CONTENT_TYPE,
        skip: skip,
        limit: limit
      ).map do |recipe|
        {
          id: recipe.id,
          title: recipe.title,
          image_url: recipe.photo.url
        }
      end
    end

    private

    def get_field_value(recipe, field)
      field = field.to_sym
      begin
        recipe.fields[field]
      rescue StandardError
        nil
      end
    end

    def get_title(contentful_recipe)
      get_field_value(contentful_recipe, 'title')
    end

    def get_description(contentful_recipe)
      get_field_value(contentful_recipe, 'description')
    end

    def get_image_url(contentful_recipe)
      photo = get_field_value(contentful_recipe, 'photo')
      begin
        photo.url
      rescue StandardError
        nil
      end
    end

    def get_chef_name(contentful_recipe)
      chef = get_field_value(contentful_recipe, 'chef')
      begin
        chef.name
      rescue StandardError
        nil
      end
    end

    def get_tags(contentful_recipe)
      tags = get_field_value(contentful_recipe, 'tags')
      begin
        tags.map(&:name).join(', ')
      rescue StandardError
        nil
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  include RecipesHelper

  def index
    skip = params[:skip] || DEFAULT_SKIP
    limit = params[:limit] || DEFAULT_LIMIT
    raise RangeError unless validate_pagination_params(skip, limit)

    @recipes = RecipeItem.fetch_recipes(skip, limit)
    respond_to do |format|
      format.html
      format.json { render json: @recipes }
    end
  rescue StandardError => e
    error_handler(e)
  end

  def show
    @recipe = RecipeItem.get_recipe(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @recipe }
    end
  rescue StandardError => e
    error_handler(e)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def markdown(text)
    options = %i[hard_wrap link_attributes autolink safe_links_only quote
                 no_intra_emphasis]
    Markdown.new(text, *options).to_html.html_safe
  end

  def error_handler(err)
    case err.class.to_s
    when /RangeError/
      render_error(416)
    when /ArgumentError/
      render_error(404)
    when /BadRequest/
      render_error(400)
    else
      render_error(500)
    end
  end

  def render_error(status)
    respond_to do |format|
      format.html { render status: status, file: "public/#{status}.html", layout: false }
      format.json do
        render json: { status: status, error: true, message: ERROR_MESSAGES[status] || 'Error' }
      end
    end
  end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
  def validate_pagination_params(skip, limit)
    valid = true
    valid &&= valid_skip(skip) if skip
    valid &&= valid_limit(limit) if limit
    valid
  end

  def valid_skip(skip)
    skip.to_i >= 0
  end

  def valid_limit(limit)
    limit.to_i >= 1 && limit.to_i <= 100
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
	  <a class="navbar-brand" href="<%= recipes_path %>">Home</a>	  
	</nav>

	<div class="container">
		<% if flash[:error] %>
			<div class="alert alert-danger"><%= flash[:error] %></div>
		<% end %>
		<% if flash[:success] %>
			<div class="alert alert-success"><%= flash[:success] %></div>
		<% end %>
		<%= yield %>
	</div>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<% @recipes.in_groups_of(2) do |group| %>
	<div class="card-group">
		<% group.compact.each do |recipe| %>
			<div class="col-sm-5">
				<div class="card contentful_product">
          <%= image_tag recipe[:image_url], class: 'card-img-top' %>
					<div class="card-block">
						<h4 class="card-title">
							<%= link_to recipe[:title], recipe_path(recipe[:id]) %>
						</h4>						
					</div>					
				</div>
			</div>
		<% end %>
	</div>
<% end %>

app/views/recipes/show.html.erb
<div class="card">
  
  <div class="card-block">
    <h1 class="card-title">
      <%= @recipe[:title] %>
    </h1>    
  </div>
  <div class="card-block col-sm-12">
    <%= image_tag @recipe[:image_url], class: 'img-fluid' %>
  </div>
  <div class="card-block">
    <p class="card-text">
      <span class="font-weight-bold">Description: </span>
      <%= markdown(@recipe[:description]) %>
    </p>
    <% if @recipe[:chef_name]%>
      <p class="card-text">
        <span class="font-weight-bold">Chef: </span>
        <%= @recipe[:chef_name] %>
      </p>
    <% end %>
    <% if @recipe[:tags] %>
      <p class="card-text">
        <span class="font-weight-bold">Tags: </span>
        <%= @recipe[:tags] %>
      </p>
    <% end %>
  </div>
    
  <div class="card-footer">
    <%= link_to 'Back', recipes_path, class: 'card-link btn btn-secondary' %>
  </div>
</div>